import chai from 'chai';

import { Tokenizer } from '../lib/tokenizer.js';

const should = chai.should();

const data = /** @type {const} */ {
  id: 'urn:uuid:7e4ed55a-2b99-48c8-a274-42819b2ddd39',
  url: 'http://example.net/status/35',
  published: '2011-09-23T10:49:00Z',
  actor: {
    displayName: 'John Smith',
    id: 'urn:uuid:bff0ecdd-a944-4d92-aed3-d6af8f13d610',
    url: 'http://example.net/status/johnsmith',
  },
  verb: 'post',
  object: {
    id: 'urn:uuid:81e43564-c66f-40c5-878b-733275229521',
    type: 'note',
    content: "<a href='http://example.com/viagra-spam'>Buy Viagra Now!</a>",
  },
};

describe('Tokenizer', () => {
  it('should be possible to create', () => {
    const tokenizer = new Tokenizer();
    should.exist(tokenizer);
  });

  it('should tokenize', async () => {
    const tokenizer = new Tokenizer();
    tokenizer.tokenize(data).should.deep.equal([
      'urn',
      'uuid',
      '7e4ed55a',
      '2b99',
      '48c8',
      'a274',
      '42819b2ddd39',
      '^urn',
      'urn^uuid',
      'uuid^7e4ed55a',
      '7e4ed55a^2b99',
      '2b99^48c8',
      '48c8^a274',
      'a274^42819b2ddd39',
      '42819b2ddd39^',
      'id=urn',
      'id=uuid',
      'id=7e4ed55a',
      'id=2b99',
      'id=48c8',
      'id=a274',
      'id=42819b2ddd39',
      'id=^urn',
      'id=urn^uuid',
      'id=uuid^7e4ed55a',
      'id=7e4ed55a^2b99',
      'id=2b99^48c8',
      'id=48c8^a274',
      'id=a274^42819b2ddd39',
      'id=42819b2ddd39^',
      'http',
      'example',
      'net',
      'status',
      '35',
      '^http',
      'http^example',
      'example^net',
      'net^status',
      'status^35',
      '35^',
      'url=http',
      'url=example',
      'url=net',
      'url=status',
      'url=35',
      'url=^http',
      'url=http^example',
      'url=example^net',
      'url=net^status',
      'url=status^35',
      'url=35^',
      '2011',
      '09',
      '23T10',
      '49',
      '00Z',
      '^2011',
      '2011^09',
      '09^23T10',
      '23T10^49',
      '49^00Z',
      '00Z^',
      'published=2011',
      'published=09',
      'published=23T10',
      'published=49',
      'published=00Z',
      'published=^2011',
      'published=2011^09',
      'published=09^23T10',
      'published=23T10^49',
      'published=49^00Z',
      'published=00Z^',
      'John',
      'Smith',
      '^John',
      'John^Smith',
      'Smith^',
      'actor.displayName=John',
      'actor.displayName=Smith',
      'actor.displayName=^John',
      'actor.displayName=John^Smith',
      'actor.displayName=Smith^',
      'urn',
      'uuid',
      'bff0ecdd',
      'a944',
      '4d92',
      'aed3',
      'd6af8f13d610',
      '^urn',
      'urn^uuid',
      'uuid^bff0ecdd',
      'bff0ecdd^a944',
      'a944^4d92',
      '4d92^aed3',
      'aed3^d6af8f13d610',
      'd6af8f13d610^',
      'actor.id=urn',
      'actor.id=uuid',
      'actor.id=bff0ecdd',
      'actor.id=a944',
      'actor.id=4d92',
      'actor.id=aed3',
      'actor.id=d6af8f13d610',
      'actor.id=^urn',
      'actor.id=urn^uuid',
      'actor.id=uuid^bff0ecdd',
      'actor.id=bff0ecdd^a944',
      'actor.id=a944^4d92',
      'actor.id=4d92^aed3',
      'actor.id=aed3^d6af8f13d610',
      'actor.id=d6af8f13d610^',
      'http',
      'example',
      'net',
      'status',
      'johnsmith',
      '^http',
      'http^example',
      'example^net',
      'net^status',
      'status^johnsmith',
      'johnsmith^',
      'actor.url=http',
      'actor.url=example',
      'actor.url=net',
      'actor.url=status',
      'actor.url=johnsmith',
      'actor.url=^http',
      'actor.url=http^example',
      'actor.url=example^net',
      'actor.url=net^status',
      'actor.url=status^johnsmith',
      'actor.url=johnsmith^',
      'post',
      '^post',
      'post^',
      'verb=post',
      'verb=^post',
      'verb=post^',
      'urn',
      'uuid',
      '81e43564',
      'c66f',
      '40c5',
      '878b',
      '733275229521',
      '^urn',
      'urn^uuid',
      'uuid^81e43564',
      '81e43564^c66f',
      'c66f^40c5',
      '40c5^878b',
      '878b^733275229521',
      '733275229521^',
      'object.id=urn',
      'object.id=uuid',
      'object.id=81e43564',
      'object.id=c66f',
      'object.id=40c5',
      'object.id=878b',
      'object.id=733275229521',
      'object.id=^urn',
      'object.id=urn^uuid',
      'object.id=uuid^81e43564',
      'object.id=81e43564^c66f',
      'object.id=c66f^40c5',
      'object.id=40c5^878b',
      'object.id=878b^733275229521',
      'object.id=733275229521^',
      'note',
      '^note',
      'note^',
      'object.type=note',
      'object.type=^note',
      'object.type=note^',
      'a',
      'href',
      'http',
      'example',
      'com',
      'viagra',
      'spam',
      'Buy',
      'Viagra',
      'Now',
      'a',
      '^a',
      'a^href',
      'href^http',
      'http^example',
      'example^com',
      'com^viagra',
      'viagra^spam',
      'spam^Buy',
      'Buy^Viagra',
      'Viagra^Now',
      'Now^a',
      'a^',
      'object.content=a',
      'object.content=href',
      'object.content=http',
      'object.content=example',
      'object.content=com',
      'object.content=viagra',
      'object.content=spam',
      'object.content=Buy',
      'object.content=Viagra',
      'object.content=Now',
      'object.content=a',
      'object.content=^a',
      'object.content=a^href',
      'object.content=href^http',
      'object.content=http^example',
      'object.content=example^com',
      'object.content=com^viagra',
      'object.content=viagra^spam',
      'object.content=spam^Buy',
      'object.content=Buy^Viagra',
      'object.content=Viagra^Now',
      'object.content=Now^a',
      'object.content=a^',
    ]);
  });
});
